[[extensions]]
name = "Render product images"
description = "Create fabric renders for this product"
handle = "render-product-images"
type = "admin_link"
uid = "6e908a94-875f-4dca-b894-1bca3a6259db"

  [[extensions.targeting]]
  target = "admin.product-details.action.link"
  url = "/app/render"
