# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "26e27f9b11b515bf3263c44b8086b253"
name = "Furniture Renderer"
application_url = "https://renderer-app-eu9fw.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://renderer-app-eu9fw.ondigitalocean.app/auth/callback" ]
